with AUnit.Assertions; use AUnit.Assertions;
with Interfaces;       use Interfaces;
with Zarr.I32;
with Zarr.I64;
with Zarr.F32;

package body Zarr_Reader_Tests is

   use AUnit.Test_Cases.Registration;

   --  Hermetic fixture (committed): a zarr v2 / blosc-zstd store generated by
   --  python-zarr.  Run the test runner from the repo root.
   Fixture : constant String := "tests/fixtures/sample.zarr";

   --  ints: 5x4 int32 in 3x3 chunks (a 2x2 chunk grid with trimmed edges),
   --  values arange(20).reshape(5,4).
   procedure Test_2D_Edges (T : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T);
      use Zarr.I32;
      A : constant Array_Data := Load (Fixture, "ints");
   begin
      Assert (A.Rank = 2, "rank is 2");
      Assert (A.Shape (1) = 5 and then A.Shape (2) = 4, "shape (5,4)");
      Assert (A.Length = 20, "20 elements");
      Assert (Element_At (A, [0, 0]) = 0, "ints[0,0] = 0");
      Assert (Element_At (A, [1, 1]) = 5, "ints[1,1] = 5 (chunk 0.0)");
      Assert (Element_At (A, [2, 3]) = 11, "ints[2,3]=11 (chunk 0.1 col trim)");
      Assert (Element_At (A, [4, 0]) = 16, "ints[4,0]=16 (chunk 1.0 row trim)");
      Assert (Element_At (A, [4, 3]) = 19, "ints[4,3]=19 (corner chunk 1.1)");
   end Test_2D_Edges;

   --  cube: 2x3x4 int32 in 2x2x2 chunks (a 1x2x2 chunk grid, edge-trimmed),
   --  values arange(24).reshape(2,3,4) -- exercises arbitrary (3-D) rank.
   procedure Test_3D (T : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T);
      use Zarr.I32;
      A : constant Array_Data := Load (Fixture, "cube");
   begin
      Assert (A.Rank = 3, "rank is 3");
      Assert (A.Shape (1) = 2 and then A.Shape (2) = 3 and then A.Shape (3) = 4,
              "shape (2,3,4)");
      Assert (A.Length = 24, "24 elements");
      Assert (Element_At (A, [0, 0, 0]) = 0, "cube[0,0,0] = 0");
      Assert (Element_At (A, [0, 1, 1]) = 5, "cube[0,1,1] = 5");
      Assert (Element_At (A, [1, 2, 0]) = 20, "cube[1,2,0] = 20 (edge chunk)");
      Assert (Element_At (A, [1, 2, 3]) = 23, "cube[1,2,3] = 23 (corner)");
   end Test_3D;

   procedure Test_1D_Int64 (T : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T);
      use Zarr.I64;
      A : constant Array_Data := Load (Fixture, "vec");
   begin
      Assert (A.Rank = 1 and then A.Shape (1) = 7, "shape (7)");
      Assert (A.Items (1) = 0, "vec[0] = 0");
      Assert (A.Items (2) = 100, "vec[1] = 100");
      Assert (A.Items (7) = 600, "vec[6] = 600");
   end Test_1D_Int64;

   procedure Test_1D_Float (T : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T);
      use Zarr.F32;
      A : constant Array_Data := Load (Fixture, "flo");
   begin
      Assert (A.Shape (1) = 4, "shape (4)");
      Assert (Element_At (A, [0]) = 1.5, "flo[0] = 1.5");
      Assert (Element_At (A, [1]) = -2.25, "flo[1] = -2.25");
      Assert (Element_At (A, [2]) = 3.125, "flo[2] = 3.125");
      Assert (Element_At (A, [3]) = 0.0, "flo[3] = 0.0");
   end Test_1D_Float;

   procedure Test_Dtype_Mismatch
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
   begin
      declare
         A : constant Zarr.F32.Array_Data := Zarr.F32.Load (Fixture, "ints");
         pragma Unreferenced (A);
      begin
         Assert (False, "reading <i4 as float should raise Unsupported");
      end;
   exception
      when Zarr.Unsupported =>
         null;  --  expected
   end Test_Dtype_Mismatch;

   procedure Test_Missing_Array
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
   begin
      declare
         A : constant Zarr.I32.Array_Data := Zarr.I32.Load (Fixture, "nope");
         pragma Unreferenced (A);
      begin
         Assert (False, "missing array should raise IO_Error");
      end;
   exception
      when Zarr.IO_Error =>
         null;  --  expected
   end Test_Missing_Array;

   procedure Register_Tests (T : in out Test) is
   begin
      Register_Routine (T, Test_2D_Edges'Access,
                        "2-D multi-chunk read with edge trimming");
      Register_Routine (T, Test_3D'Access,
                        "3-D multi-chunk read (arbitrary rank)");
      Register_Routine (T, Test_1D_Int64'Access, "1-D int64 read");
      Register_Routine (T, Test_1D_Float'Access, "1-D float32 read");
      Register_Routine (T, Test_Dtype_Mismatch'Access,
                        "dtype mismatch raises Unsupported");
      Register_Routine (T, Test_Missing_Array'Access,
                        "missing array raises IO_Error");
   end Register_Tests;

   overriding
   function Name (T : Test) return AUnit.Message_String is
      pragma Unreferenced (T);
   begin
      return AUnit.Format ("Zarr readers (blosc decompress + chunk assembly)");
   end Name;

end Zarr_Reader_Tests;
